# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-01 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'family',
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'friend',
            },
        ),
        migrations.CreateModel(
            name='GCM',
            fields=[
                ('u_id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('regid', models.CharField(blank=256, max_length=256, null=True)),
            ],
            options={
                'db_table': 'gcm',
            },
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'other',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('phone', models.CharField(blank=True, max_length=256, null=True)),
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('oauth', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
